import argparse
import re

# ── CLI ──────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Amalgamate fast_float.")
parser.add_argument(
    "--license",
    default="TRIPLE",
    choices=["DUAL", "TRIPLE", "MIT", "APACHE", "BOOST"],
    help="choose license",
)
parser.add_argument("--output", default="", help="output file (stdout if none)")
args = parser.parse_args()

# ── text parts ───────────────────────────────────────────────────────
processed_files = {}

# authors
for filename in ["AUTHORS", "CONTRIBUTORS"]:
    with open(filename, encoding="utf8") as f:
        text = ""
        for line in f:
            if filename == "AUTHORS":
                text += "// fast_float by " + line
            if filename == "CONTRIBUTORS":
                text += "// with contributions from " + line
        processed_files[filename] = text + "//\n//\n"

# licenses
for filename in ["LICENSE-MIT", "LICENSE-APACHE", "LICENSE-BOOST"]:
    lines = []
    with open(filename, encoding="utf8") as f:
        lines = f.readlines()

    if filename == "LICENSE-APACHE":
        lines = ["   Copyright 2021 The fast_float authors\n", *lines[179:-1]]

    text = ""
    for line in lines:
        line = line.strip()
        if len(line):
            line = "    " + line
        text += "//" + line + "\n"
    processed_files[filename] = text


def license_content(license_arg):
    result = []
    if license_arg == "TRIPLE":
        result += [
            "// Licensed under the Apache License, Version 2.0, or the\n",
            "// MIT License or the Boost License. This file may not be copied,\n",
            "// modified, or distributed except according to those terms.\n",
            "//\n",
        ]
    if license_arg == "DUAL":
        result += [
            "// Licensed under the Apache License, Version 2.0, or the\n",
            "// MIT License at your option. This file may not be copied,\n",
            "// modified, or distributed except according to those terms.\n",
            "//\n",
        ]

    if license_arg in ("DUAL", "TRIPLE", "MIT"):
        result.append("// MIT License Notice\n//\n")
        result.append(processed_files["LICENSE-MIT"])
        result.append("//\n")
    if license_arg in ("DUAL", "TRIPLE", "APACHE"):
        result.append("// Apache License (Version 2.0) Notice\n//\n")
        result.append(processed_files["LICENSE-APACHE"])
        result.append("//\n")
    if license_arg in ("TRIPLE", "BOOST"):
        result.append("// BOOST License Notice\n//\n")
        result.append(processed_files["LICENSE-BOOST"])
        result.append("//\n")

    return result


# ── source code ──────────────────────────────────────────────────────

# Read every source file once (raw, no processing)
source_files = {}
for filename in [
    "api.h",
    "common.h",
    "bigint.h",
    "parse.h",
    "digit_comparison.h",
    "ffc.h",
]:
    with open("src/" + filename, encoding="utf8") as f:
        source_files[filename] = f.read()


INCLUDE_RE = re.compile(r'^#include "([^"]+)"\s*$')


def expand_source(filename, already_included=None):
    """Recursively expand a source file, replacing #include "x.h" with
    the contents of x.h (with its own #include "..." lines expanded too).

    Each file is expanded at most once; subsequent #include of the same
    file are silently dropped (the include-guard macros still exist, but
    this avoids emitting empty guarded blocks).
    """
    if already_included is None:
        already_included = set()

    if filename in already_included:
        return ""
    already_included.add(filename)

    lines = source_files[filename].splitlines(keepends=True)
    parts = []
    for line in lines:
        m = INCLUDE_RE.match(line)
        if m:
            included = m.group(1)
            if included in source_files:
                # Inline the included file (recursively)
                parts.append(expand_source(included, already_included))
            else:
                # System or unknown include — keep as-is
                parts.append(line)
        else:
            parts.append(line)
    return "".join(parts)


amalgamated_code = expand_source("ffc.h")

# ── assemble ─────────────────────────────────────────────────────────
AUTOGEN_DISCLAIMER = (
    "// This file is auto-generated by amalgamate.py from the sources in src/.\n"
    "// Do not edit it directly — edit the source files and regenerate.\n"
    "//\n"
    "\n"
)

text = "".join(
    [
        processed_files["AUTHORS"],
        processed_files["CONTRIBUTORS"],
        *license_content(args.license),
        "\n",
        AUTOGEN_DISCLAIMER,
        amalgamated_code,
    ]
)

if args.output:
    with open(args.output, "wt", encoding="utf8") as f:
        f.write(text)
else:
    print(text)
