name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: print gcc version
        run: gcc -v
      - name: tronko-assign make clean
        run: make clean
        working-directory: ./tronko-assign
      - name: build tronko-assign debug
        run: make debug
        working-directory: ./tronko-assign
      - name: rename tronko-assign debug
        run: mv tronko-assign/tronko-assign bin/tronko-assign-debug
      - name: build tronko-assign
        run: make
        working-directory: ./tronko-assign
      - name: rename tronko-assign debug
        run: mv tronko-assign/tronko-assign bin/tronko-assign
      - name: tronko-build make clean
        run: make clean
        working-directory: ./tronko-build
      - name: build tronko-build debug
        run: make debug
        working-directory: ./tronko-build
      - name: rename tronko-build debug
        run: mv tronko-build/tronko-build bin/tronko-build-debug
      - name: build tronko-build
        run: make
        working-directory: ./tronko-build
      - name: rename tronko-build debug
        run: mv tronko-build/tronko-build bin/tronko-build
      - name: Upload tronko.zip
        uses: actions/upload-artifact@v3
        with:
          name: tronko
          path: bin
      
